function[zhat_tilde] = pred_measurement(xhat,r_fi,simpar)
%uses the position to feature generated by synth_measurement
rhat_i = xhat(simpar.states.ixf.pos);

Ti2b = calc_attitude(xhat, simpar);
Tb2c = eye(3,3); %for now (this will be known)

%Predict LOS vector
lc = Tb2c*Ti2b*(r_fi-rhat_i);
lx = lc(1);
ly = lc(2);
lz = lc(3);

zhat_tilde = [lx/lz;ly/lz];

end